engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    checks:
      Similar code:
        enabled: false
  radon:
    enabled: true
  pep8:
    enabled: true

ratings:
  paths:
    - "**.py"